"""Initial

Revision ID: 63c80ff9b26e
Revises: edef006f7684
Create Date: 2025-06-30 17:00:48.515776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c80ff9b26e'
down_revision: Union[str, None] = 'edef006f7684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('images', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('places', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('places', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'longitude')
    op.drop_column('places', 'latitude')
    op.drop_column('places', 'images')
    # ### end Alembic commands ###
