"""add regions

Revision ID: b91cb24bb98c
Revises: 76e93c2d2509
Create Date: 2025-04-11 08:51:04.670909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91cb24bb98c'
down_revision: Union[str, None] = '76e93c2d2509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
                    sa.Column('region_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('list', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('region_id')
                    )
    op.create_index(op.f('ix_regions_region_id'), 'regions', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regions_region_id'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
