"""add places

Revision ID: edef006f7684
Revises: b91cb24bb98c
Create Date: 2025-04-11 09:11:23.030411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edef006f7684'
down_revision: Union[str, None] = 'b91cb24bb98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
                    sa.Column('place_id', sa.UUID(), nullable=True),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('region_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('place_id')
                    )
    op.create_index(op.f('ix_places_place_id'), 'places', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regions', 'region_id',
                    existing_type=sa.Integer(),
                    type_=sa.UUID(),
                    existing_nullable=False,
                    autoincrement=True)
    op.drop_index(op.f('ix_places_place_id'), table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
